/*****shops*****/
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const GET_SHOP_INFO_SUCCESS = 'GET_SHOP_INFO_SUCCESS'
export const GET_SHOP_INFO_FAIL = 'GET_SHOP_INFO_FAIL'
export const UPDATE_SHOP_INFO_SUCCESS = 'UPDATE_SHOP_INFO_SUCCESS'
export const UPDATE_SHOP_INFO_FAIL = 'UPDATE_SHOP_INFO_FAIL'

/******menu******/
export const GET_SHOP_MENU_SUCCESS = 'GET_SHOP_MENU_SUCCESS'
export const GET_SHOP_MENU_FAIL = 'GET_SHOP_MENU_FAIL'
export const UPDATE_SHOP_MENU_SUCCESS = 'UPDATE_SHOP_MENU_SUCCESS'
export const UPDATE_SHOP_MENU_FAIL = 'UPDATE_SHOP_MENU_FAIL'


/******bils**********/
export const GET_SHOP_ORDER_LIST_SUCCESS = 'GET_SHOP_ORDER_LIST_SUCCESS'
export const GET_SHOP_ORDER_LIST_FAIL = 'GET_SHOP_ORDER_LIST_FAIL'
