/*****shops*****/
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const GET_SHOP_INFO_SUCCESS = 'GET_SHOP_INFO_SUCCESS'
export const GET_SHOP_INFO_FAIL = 'GET_SHOP_INFO_FAIL'
export const UPDATE_SHOP_INFO_SUCCESS = 'UPDATE_SHOP_INFO_SUCCESS'
export const UPDATE_SHOP_INFO_FAIL = 'UPDATE_SHOP_INFO_FAIL'

/******menu******/
export const GET_SHOP_MENU_SUCCESS = 'GET_SHOP_MENU_SUCCESS'
export const GET_SHOP_MENU_FAIL = 'GET_SHOP_MENU_FAIL'
export const UPDATE_SHOP_MENU_SUCCESS = 'UPDATE_SHOP_MENU_SUCCESS'
export const UPDATE_SHOP_MENU_FAIL = 'UPDATE_SHOP_MENU_FAIL'


/******bils**********/
export const GET_SHOP_ORDER_LIST_SUCCESS = 'GET_SHOP_ORDER_LIST_SUCCESS'
export const GET_SHOP_ORDER_LIST_FAIL = 'GET_SHOP_ORDER_LIST_FAIL'
export const GET_SHOP_ORDER_IN_PROGRESS_LIST_SUCCESS = 'GET_SHOP_ORDER_IN_PROGRESS_LIST_SUCCESS'
export const GET_SHOP_ORDER_IN_PROGRESS_LIST_FAIL = 'GET_SHOP_ORDER_IN_PROGRESS_LIST_FAIL'
export const GET_SHOP_HISTORY_ORDER_LIST_SUCCESS = 'GET_SHOP_HISTORY_ORDER_LIST_SUCCESS'
export const GET_SHOP_HISTORY_ORDER_LIST_FAIL = 'GET_SHOP_HISTORY_ORDER_LIST_FAIL'
export const ENSUER_ORDER_SUCCESS = 'ENSUER_ORDER_SUCCESS'
export const ENSURE_ORDER_FAIL = 'ENSURE_ORDER_FAIL'
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL'

/*******uploadFile********/
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL'
