/*****users*****/
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL'
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL'

/*****shop List*****/
export const GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS'
export const GET_SHOP_LIST_FAIL = 'GET_SHOP_LIST_FAIL'

/******shop menu************/
export const GET_SHOP_MENU_SUCCESS = 'GET_SHOP_MENU_SUCCESS'
export const GET_SHOP_MENU_FAIL = 'GET_SHOP_MENU_FAIL'
export const ADD_SHOP_DISH_NUM_SUCCESS = 'ADD_SHOP_DISH_NUM_SUCCESS'
export const SUB_SHOP_DISH_NUM_SUCCESS = 'SUB_SHOP_DISH_NUM_SUCCESS'
export const GET_SHOP_INFO_SUCCESS = 'GET_SHOP_INFO_SUCCESS'
export const GET_SHOP_INFO_FAIL = 'GET_SHOP_INFO_FAIL'

/*****bills*******************/
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAIL = 'ORDER_FAIL'
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'
export const GET_ORDER_LIST_FAIL = 'GET_ORDER_LIST_FAIL'
export const GET_ORDER_INFO_SUCCESS = 'GET_ORDER_INFO_SUCCESS'
export const GET_ORDER_INFO_FAIL = 'GET_ORDER_INFO_FAIL'
export const ENSURE_RECEIVED_ORDER_SUCCESS = 'ENSURE_RECEIVED_ORDER_SUCCESS'
export const ENSURE_RECEIVED_ORDER_FAIL = 'ENSURE_RECEIVED_ORDER_FAIL'
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL'

